export const SOCIAL_ROUTE: string = '/social-auth'
export const GOOGLE_CLIENT_ID_ROUTE: string = '/google-auth-client-id'
export const GOOGLE_PROFILE_SAVE_ROUTE: string = '/google-auth-save'
export const VK_ACCESS_TOKEN_ROUTE: string = '/vk-get-app-id'
export const VK_GET_USER_DATA_ROUTE: string = '/vk-get-user-data'
